apiVersion: v1
kind: Namespace
metadata:
  name: hairpin-proxy

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: haproxy-cfg
  namespace: hairpin-proxy
data:
  value: |
    defaults
      timeout client 1800s
      timeout connect 1800s
      timeout server 1800s
    frontend fe_80
      bind *:80
      mode http
      use_backend be_ingress_80
    backend be_ingress_80
      mode http
      server my_server "${TARGET_SERVER}:80"

    frontend fe_443
      bind *:443
      mode http
      use_backend be_ingress_443
    backend be_ingress_443
      mode http
      server my_server "${TARGET_SERVER}:443"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hairpin-proxy-haproxy
  name: hairpin-proxy-haproxy
  namespace: hairpin-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hairpin-proxy-haproxy
  template:
    metadata:
      labels:
        app: hairpin-proxy-haproxy
    spec:
      containers:
        - image: compumike/hairpin-proxy-haproxy:0.2.1
          name: main
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "200Mi"
              cpu: "50m"
          env:
            - name: TARGET_SERVER
              value: ingress-nginx-controller.ingress-nginx.svc.cluster.local
          volumeMounts:
            - mountPath: /usr/local/etc/haproxy/
              name: haproxy-cfg-cm
              readOnly: true
      volumes:
        - name: haproxy-cfg-cm
          configMap:
            defaultMode: 400
            items:
              - key: value
                path: haproxy.cfg
            name: haproxy-cfg

---
apiVersion: v1
kind: Service
metadata:
  name: hairpin-proxy
  namespace: hairpin-proxy
spec:
  selector:
    app: hairpin-proxy-haproxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: hairpin-proxy-controller-sa
  namespace: hairpin-proxy

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hairpin-proxy-controller-cr
rules:
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hairpin-proxy-controller-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hairpin-proxy-controller-cr
subjects:
  - kind: ServiceAccount
    name: hairpin-proxy-controller-sa
    namespace: hairpin-proxy

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hairpin-proxy-controller-r
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - coredns
    verbs:
      - get
      - watch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hairpin-proxy-controller-rb
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hairpin-proxy-controller-r
subjects:
  - kind: ServiceAccount
    name: hairpin-proxy-controller-sa
    namespace: hairpin-proxy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hairpin-proxy-controller
  name: hairpin-proxy-controller
  namespace: hairpin-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hairpin-proxy-controller
  template:
    metadata:
      labels:
        app: hairpin-proxy-controller
    spec:
      serviceAccountName: hairpin-proxy-controller-sa
      securityContext:
        runAsUser: 405
        runAsGroup: 65533
      containers:
        - image: compumike/hairpin-proxy-controller:0.2.1
          name: main
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "50m"
